name: CustomAreas
main: CustomAreas\Main
version: 1.1
api: [2.0.0 , 3.0.0-ALPHA1 , 3.0.0-ALPHA2 , 3.0.0-ALPHA9]
author: luca28pet
description: Protect areas in your server
website: https://github.com/luca28pet/CustomAreas
commands:
 customareas:
  description: Manage areas
  usage: "/ca pos1|pos2|create|delete|whitelist"
  aliases: [ca]
  permission: customareas.command
permissions:
 customareas.command:
  description: "Allows the user to manage areas"
  default: true
 customareas.bypass:
  description: "Allows to have admin features"
  default: op
